server:
  port: 8080
spring:
  application:
    name: employee-service
employee-service:
  greeting: hello employee
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
