server:
  port: 8080
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
      
employee-service:
  greeting: hello employee
  
spring:
  application:
    name: employee-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/viswa?createDatabaseIfNotExist=true
    username: root
    password: Akshay01!
    driver-class-name: com.mysql.jdbc.Driver
    

