server:
  port: 8090
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
      
student-service:
  greeting: hellostudent
  
spring:
  application:
    name: student-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/xxxx?createDatabaseIfNotExist=true
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.jdbc.Driver
    

