server:
  port: 8090
spring:
  application:
    name: student-service
   jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    datasource:
      url:  jdbc:mysql://localhost:3306/viswa
      username: root
      password: Akshay01!
student-service:
  greeting: hellostudent
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/  
